// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v5.28.3
// source: proto/cart.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "cart";

export interface Cart {
  userId: string;
  items: CartItem[];
  totalPrice: number;
}

export interface CartItem {
  productId: string;
  quantity: number;
}

export interface GetCartRequest {
  userId: number;
}

export interface GetCartResponse {
  cart: Cart | undefined;
}

export interface UpdateCartRequest {
  userId: string;
  items: CartItem[];
}

export interface UpdateCartResponse {
  cart: Cart | undefined;
}

export interface DeleteCartRequest {
  userId: number;
}

export interface DeleteCartResponse {
  success: boolean;
}

export const CART_PACKAGE_NAME = "cart";

export interface CartServiceClient {
  getCart(request: GetCartRequest): Observable<GetCartResponse>;

  updateCart(request: UpdateCartRequest): Observable<UpdateCartResponse>;

  deleteCart(request: DeleteCartRequest): Observable<DeleteCartResponse>;
}

export interface CartServiceController {
  getCart(request: GetCartRequest): Promise<GetCartResponse> | Observable<GetCartResponse> | GetCartResponse;

  updateCart(
    request: UpdateCartRequest,
  ): Promise<UpdateCartResponse> | Observable<UpdateCartResponse> | UpdateCartResponse;

  deleteCart(
    request: DeleteCartRequest,
  ): Promise<DeleteCartResponse> | Observable<DeleteCartResponse> | DeleteCartResponse;
}

export function CartServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getCart", "updateCart", "deleteCart"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CartService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CartService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CART_SERVICE_NAME = "CartService";
