# docker compose up -d

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'

  server:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   verison: 'v1.0.0'
      # cache_from:
      #   - node:20
      #   - node:20-slim
    container_name: express-server
    ports:
      - '8964:8964'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    # That means the server should start after Redis has started.
    depends_on:
      - redis
