FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm
RUN pnpm install

COPY . .

RUN pnpm build gateway

FROM node:20-slim AS runner

WORKDIR /app

COPY --from=builder /app/dist/apps/gateway ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package.json .
COPY proto ./proto

ENV NODE_ENV=production
EXPOSE 10086

CMD ["node", "dist/main"]