# docker compose up -d

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-server
    ports:
      - '8964:8964'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
