apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: commerce/gateway-service:1.0.0
          ports:
            - containerPort: 10086
          env:
            - name: ORDER_SERVICE_URL
              value: order-service:50051
            - name: PRODUCT_SERVICE_URL
              value: product-service:50052
