apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: commerce/order-service:1.0.0
          ports:
            - containerPort: 10087
          env:
            - name: NODE_ENV
              value: production
